# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payslip/v1/payslip.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payslip/v1/payslip.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18payslip/v1/payslip.proto\x12\npayslip.v1\"\xe9\x01\n\x16GeneratePayslipRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12;\n\x05order\x18\x02 \x01(\x0b\x32,.payslip.v1.GeneratePayslipRequest.OrderData\x1a\x81\x01\n\tOrderData\x12\x0f\n\x07orderid\x18\x01 \x01(\x03\x12@\n\x05items\x18\x02 \x03(\x0b\x32\x31.payslip.v1.GeneratePayslipRequest.OrderData.Item\x1a!\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"%\n\x17GeneratePayslipResponse\x12\n\n\x02id\x18\x01 \x01(\t\"F\n\x11SendPaylipRequest\x12\x0e\n\x06userid\x18\x01 \x01(\x05\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\"!\n\x13SendPayslipResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\x1f\n\x11GetPayslipRequest\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x12GetPayslipResponse\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32\x89\x02\n\x0f\x44ocumentService\x12Z\n\x0fGeneratePayslip\x12\".payslip.v1.GeneratePayslipRequest\x1a#.payslip.v1.GeneratePayslipResponse\x12M\n\x0bSendPayslip\x12\x1d.payslip.v1.SendPaylipRequest\x1a\x1f.payslip.v1.SendPayslipResponse\x12K\n\nGetPayslip\x12\x1d.payslip.v1.GetPayslipRequest\x1a\x1e.payslip.v1.GetPayslipResponseB9Z7github.com/Nublnv/go-service/proto/payslip/v1;payslipv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payslip.v1.payslip_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z7github.com/Nublnv/go-service/proto/payslip/v1;payslipv1'
  _globals['_GENERATEPAYSLIPREQUEST']._serialized_start=41
  _globals['_GENERATEPAYSLIPREQUEST']._serialized_end=274
  _globals['_GENERATEPAYSLIPREQUEST_ORDERDATA']._serialized_start=145
  _globals['_GENERATEPAYSLIPREQUEST_ORDERDATA']._serialized_end=274
  _globals['_GENERATEPAYSLIPREQUEST_ORDERDATA_ITEM']._serialized_start=241
  _globals['_GENERATEPAYSLIPREQUEST_ORDERDATA_ITEM']._serialized_end=274
  _globals['_GENERATEPAYSLIPRESPONSE']._serialized_start=276
  _globals['_GENERATEPAYSLIPRESPONSE']._serialized_end=313
  _globals['_SENDPAYLIPREQUEST']._serialized_start=315
  _globals['_SENDPAYLIPREQUEST']._serialized_end=385
  _globals['_SENDPAYSLIPRESPONSE']._serialized_start=387
  _globals['_SENDPAYSLIPRESPONSE']._serialized_end=420
  _globals['_GETPAYSLIPREQUEST']._serialized_start=422
  _globals['_GETPAYSLIPREQUEST']._serialized_end=453
  _globals['_GETPAYSLIPRESPONSE']._serialized_start=455
  _globals['_GETPAYSLIPRESPONSE']._serialized_end=510
  _globals['_DOCUMENTSERVICE']._serialized_start=513
  _globals['_DOCUMENTSERVICE']._serialized_end=778
# @@protoc_insertion_point(module_scope)
