# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from payslip.v1 import payslip_pb2 as payslip_dot_v1_dot_payslip__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in payslip/v1/payslip_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DocumentServiceStub(object):
    """Service for work with payslips documents
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GeneratePayslip = channel.unary_unary(
                '/payslip.v1.DocumentService/GeneratePayslip',
                request_serializer=payslip_dot_v1_dot_payslip__pb2.GeneratePayslipRequest.SerializeToString,
                response_deserializer=payslip_dot_v1_dot_payslip__pb2.GeneratePayslipResponse.FromString,
                _registered_method=True)
        self.SendPayslip = channel.unary_unary(
                '/payslip.v1.DocumentService/SendPayslip',
                request_serializer=payslip_dot_v1_dot_payslip__pb2.SendPaylipRequest.SerializeToString,
                response_deserializer=payslip_dot_v1_dot_payslip__pb2.SendPayslipResponse.FromString,
                _registered_method=True)
        self.GetPayslip = channel.unary_unary(
                '/payslip.v1.DocumentService/GetPayslip',
                request_serializer=payslip_dot_v1_dot_payslip__pb2.GetPayslipRequest.SerializeToString,
                response_deserializer=payslip_dot_v1_dot_payslip__pb2.GetPayslipResponse.FromString,
                _registered_method=True)


class DocumentServiceServicer(object):
    """Service for work with payslips documents
    """

    def GeneratePayslip(self, request, context):
        """Method for generate payslip in Python service and save it in mongo. Returns payslipid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendPayslip(self, request, context):
        """Method uses for send email with payslip
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPayslip(self, request, context):
        """Method returns payslip document by id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GeneratePayslip': grpc.unary_unary_rpc_method_handler(
                    servicer.GeneratePayslip,
                    request_deserializer=payslip_dot_v1_dot_payslip__pb2.GeneratePayslipRequest.FromString,
                    response_serializer=payslip_dot_v1_dot_payslip__pb2.GeneratePayslipResponse.SerializeToString,
            ),
            'SendPayslip': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPayslip,
                    request_deserializer=payslip_dot_v1_dot_payslip__pb2.SendPaylipRequest.FromString,
                    response_serializer=payslip_dot_v1_dot_payslip__pb2.SendPayslipResponse.SerializeToString,
            ),
            'GetPayslip': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPayslip,
                    request_deserializer=payslip_dot_v1_dot_payslip__pb2.GetPayslipRequest.FromString,
                    response_serializer=payslip_dot_v1_dot_payslip__pb2.GetPayslipResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payslip.v1.DocumentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('payslip.v1.DocumentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DocumentService(object):
    """Service for work with payslips documents
    """

    @staticmethod
    def GeneratePayslip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payslip.v1.DocumentService/GeneratePayslip',
            payslip_dot_v1_dot_payslip__pb2.GeneratePayslipRequest.SerializeToString,
            payslip_dot_v1_dot_payslip__pb2.GeneratePayslipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendPayslip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payslip.v1.DocumentService/SendPayslip',
            payslip_dot_v1_dot_payslip__pb2.SendPaylipRequest.SerializeToString,
            payslip_dot_v1_dot_payslip__pb2.SendPayslipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPayslip(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/payslip.v1.DocumentService/GetPayslip',
            payslip_dot_v1_dot_payslip__pb2.GetPayslipRequest.SerializeToString,
            payslip_dot_v1_dot_payslip__pb2.GetPayslipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
