services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/pg_data
    hostname: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - go-service
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres:/data/pg_data

  clickhouse-server:
    image: clickhouse/clickhouse-server:26.2.4 # Use a specific version for stability (e.g., 23.10)
    hostname: clickhouse
    ports:
      - "8123:8123" # HTTP interface port
      - "9000:9000" # Native client port
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      # Optional: Set default user password and database
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - go-service

  go-service:
    build:
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      REST_HOST: 0.0.0.0
      REST_PORT: 443
      TLS_PATH: /src/certs
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      MIGRATIONS_PATH: /src/migrations
    # entrypoint: ["/bin/bash", "-c", "sleep infinity"]
    image: go-service-linux-arm64
    hostname: go-service
    ports:
      - 8443:443
    networks:
      - go-service
    volumes:
      - tls:/src/certs

volumes:
  postgres:
    driver: local
    name: postgres_data
    driver_opts:
      type: none
      o: bind
      device: ${POSTGRES_DATA}
  tls:
    driver: local
    name: certs
    driver_opts:
      type: none
      o: bind
      device: ${TLS_PATH}
  clickhouse_data:
    driver: local
    name: clickhouse_data
    driver_opts:
      type: none
      o: bind
      device: ${CLICKHOUSE_DATA}
  clickhouse_logs:
    driver: local
    name: clickhouse_logs
    driver_opts:
      type: none
      o: bind
      device: ${CLICKHOUSE_LOGS}

networks:
  go-service:
    driver: bridge