// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: payslip/v1/payslip.proto

package payslipv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DocumentService_GeneratePayslip_FullMethodName = "/payslip.v1.DocumentService/GeneratePayslip"
	DocumentService_SendPayslip_FullMethodName     = "/payslip.v1.DocumentService/SendPayslip"
	DocumentService_GetPayslip_FullMethodName      = "/payslip.v1.DocumentService/GetPayslip"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for work with payslips documents
type DocumentServiceClient interface {
	// Method for generate payslip in Python service and save it in mongo. Returns payslipid
	GeneratePayslip(ctx context.Context, in *GeneratePayslipRequest, opts ...grpc.CallOption) (*GeneratePayslipResponse, error)
	// Method uses for send email with payslip
	SendPayslip(ctx context.Context, in *SendPaylipRequest, opts ...grpc.CallOption) (*SendPayslipResponse, error)
	// Method returns payslip document by id
	GetPayslip(ctx context.Context, in *GetPayslipRequest, opts ...grpc.CallOption) (*GetPayslipResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) GeneratePayslip(ctx context.Context, in *GeneratePayslipRequest, opts ...grpc.CallOption) (*GeneratePayslipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePayslipResponse)
	err := c.cc.Invoke(ctx, DocumentService_GeneratePayslip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) SendPayslip(ctx context.Context, in *SendPaylipRequest, opts ...grpc.CallOption) (*SendPayslipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendPayslipResponse)
	err := c.cc.Invoke(ctx, DocumentService_SendPayslip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetPayslip(ctx context.Context, in *GetPayslipRequest, opts ...grpc.CallOption) (*GetPayslipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayslipResponse)
	err := c.cc.Invoke(ctx, DocumentService_GetPayslip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
//
// Service for work with payslips documents
type DocumentServiceServer interface {
	// Method for generate payslip in Python service and save it in mongo. Returns payslipid
	GeneratePayslip(context.Context, *GeneratePayslipRequest) (*GeneratePayslipResponse, error)
	// Method uses for send email with payslip
	SendPayslip(context.Context, *SendPaylipRequest) (*SendPayslipResponse, error)
	// Method returns payslip document by id
	GetPayslip(context.Context, *GetPayslipRequest) (*GetPayslipResponse, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) GeneratePayslip(context.Context, *GeneratePayslipRequest) (*GeneratePayslipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePayslip not implemented")
}
func (UnimplementedDocumentServiceServer) SendPayslip(context.Context, *SendPaylipRequest) (*SendPayslipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendPayslip not implemented")
}
func (UnimplementedDocumentServiceServer) GetPayslip(context.Context, *GetPayslipRequest) (*GetPayslipResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayslip not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_GeneratePayslip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePayslipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GeneratePayslip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GeneratePayslip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GeneratePayslip(ctx, req.(*GeneratePayslipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_SendPayslip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendPaylipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).SendPayslip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_SendPayslip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).SendPayslip(ctx, req.(*SendPaylipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetPayslip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayslipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetPayslip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetPayslip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetPayslip(ctx, req.(*GetPayslipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payslip.v1.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePayslip",
			Handler:    _DocumentService_GeneratePayslip_Handler,
		},
		{
			MethodName: "SendPayslip",
			Handler:    _DocumentService_SendPayslip_Handler,
		},
		{
			MethodName: "GetPayslip",
			Handler:    _DocumentService_GetPayslip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payslip/v1/payslip.proto",
}
