// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: payslip/v1/payslip.proto

package payslipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GeneratePayslipRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Userid        int32                             `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Order         *GeneratePayslipRequest_OrderData `protobuf:"bytes,2,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayslipRequest) Reset() {
	*x = GeneratePayslipRequest{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayslipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayslipRequest) ProtoMessage() {}

func (x *GeneratePayslipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayslipRequest.ProtoReflect.Descriptor instead.
func (*GeneratePayslipRequest) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratePayslipRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *GeneratePayslipRequest) GetOrder() *GeneratePayslipRequest_OrderData {
	if x != nil {
		return x.Order
	}
	return nil
}

type GeneratePayslipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayslipResponse) Reset() {
	*x = GeneratePayslipResponse{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayslipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayslipResponse) ProtoMessage() {}

func (x *GeneratePayslipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayslipResponse.ProtoReflect.Descriptor instead.
func (*GeneratePayslipResponse) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratePayslipResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SendPaylipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userid        int32                  `protobuf:"varint,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPaylipRequest) Reset() {
	*x = SendPaylipRequest{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPaylipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPaylipRequest) ProtoMessage() {}

func (x *SendPaylipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPaylipRequest.ProtoReflect.Descriptor instead.
func (*SendPaylipRequest) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{2}
}

func (x *SendPaylipRequest) GetUserid() int32 {
	if x != nil {
		return x.Userid
	}
	return 0
}

func (x *SendPaylipRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *SendPaylipRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type SendPayslipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPayslipResponse) Reset() {
	*x = SendPayslipResponse{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPayslipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPayslipResponse) ProtoMessage() {}

func (x *SendPayslipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPayslipResponse.ProtoReflect.Descriptor instead.
func (*SendPayslipResponse) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{3}
}

func (x *SendPayslipResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type GetPayslipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayslipRequest) Reset() {
	*x = GetPayslipRequest{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayslipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayslipRequest) ProtoMessage() {}

func (x *GetPayslipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayslipRequest.ProtoReflect.Descriptor instead.
func (*GetPayslipRequest) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{4}
}

func (x *GetPayslipRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPayslipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPayslipResponse) Reset() {
	*x = GetPayslipResponse{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPayslipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPayslipResponse) ProtoMessage() {}

func (x *GetPayslipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPayslipResponse.ProtoReflect.Descriptor instead.
func (*GetPayslipResponse) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{5}
}

func (x *GetPayslipResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetPayslipResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GeneratePayslipRequest_OrderData struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Orderid       int64                                    `protobuf:"varint,1,opt,name=orderid,proto3" json:"orderid,omitempty"`
	Items         []*GeneratePayslipRequest_OrderData_Item `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayslipRequest_OrderData) Reset() {
	*x = GeneratePayslipRequest_OrderData{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayslipRequest_OrderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayslipRequest_OrderData) ProtoMessage() {}

func (x *GeneratePayslipRequest_OrderData) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayslipRequest_OrderData.ProtoReflect.Descriptor instead.
func (*GeneratePayslipRequest_OrderData) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{0, 0}
}

func (x *GeneratePayslipRequest_OrderData) GetOrderid() int64 {
	if x != nil {
		return x.Orderid
	}
	return 0
}

func (x *GeneratePayslipRequest_OrderData) GetItems() []*GeneratePayslipRequest_OrderData_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type GeneratePayslipRequest_OrderData_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePayslipRequest_OrderData_Item) Reset() {
	*x = GeneratePayslipRequest_OrderData_Item{}
	mi := &file_payslip_v1_payslip_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePayslipRequest_OrderData_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePayslipRequest_OrderData_Item) ProtoMessage() {}

func (x *GeneratePayslipRequest_OrderData_Item) ProtoReflect() protoreflect.Message {
	mi := &file_payslip_v1_payslip_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePayslipRequest_OrderData_Item.ProtoReflect.Descriptor instead.
func (*GeneratePayslipRequest_OrderData_Item) Descriptor() ([]byte, []int) {
	return file_payslip_v1_payslip_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *GeneratePayslipRequest_OrderData_Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GeneratePayslipRequest_OrderData_Item) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_payslip_v1_payslip_proto protoreflect.FileDescriptor

const file_payslip_v1_payslip_proto_rawDesc = "" +
	"\n" +
	"\x18payslip/v1/payslip.proto\x12\n" +
	"payslip.v1\"\x93\x02\n" +
	"\x16GeneratePayslipRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x05R\x06userid\x12B\n" +
	"\x05order\x18\x02 \x01(\v2,.payslip.v1.GeneratePayslipRequest.OrderDataR\x05order\x1a\x9c\x01\n" +
	"\tOrderData\x12\x18\n" +
	"\aorderid\x18\x01 \x01(\x03R\aorderid\x12G\n" +
	"\x05items\x18\x02 \x03(\v21.payslip.v1.GeneratePayslipRequest.OrderData.ItemR\x05items\x1a,\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\")\n" +
	"\x17GeneratePayslipResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"a\n" +
	"\x11SendPaylipRequest\x12\x16\n" +
	"\x06userid\x18\x01 \x01(\x05R\x06userid\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\"%\n" +
	"\x13SendPayslipResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"#\n" +
	"\x11GetPayslipRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x12GetPayslipResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2\x89\x02\n" +
	"\x0fDocumentService\x12Z\n" +
	"\x0fGeneratePayslip\x12\".payslip.v1.GeneratePayslipRequest\x1a#.payslip.v1.GeneratePayslipResponse\x12M\n" +
	"\vSendPayslip\x12\x1d.payslip.v1.SendPaylipRequest\x1a\x1f.payslip.v1.SendPayslipResponse\x12K\n" +
	"\n" +
	"GetPayslip\x12\x1d.payslip.v1.GetPayslipRequest\x1a\x1e.payslip.v1.GetPayslipResponseB9Z7github.com/Nublnv/go-service/proto/payslip/v1;payslipv1b\x06proto3"

var (
	file_payslip_v1_payslip_proto_rawDescOnce sync.Once
	file_payslip_v1_payslip_proto_rawDescData []byte
)

func file_payslip_v1_payslip_proto_rawDescGZIP() []byte {
	file_payslip_v1_payslip_proto_rawDescOnce.Do(func() {
		file_payslip_v1_payslip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payslip_v1_payslip_proto_rawDesc), len(file_payslip_v1_payslip_proto_rawDesc)))
	})
	return file_payslip_v1_payslip_proto_rawDescData
}

var file_payslip_v1_payslip_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_payslip_v1_payslip_proto_goTypes = []any{
	(*GeneratePayslipRequest)(nil),                // 0: payslip.v1.GeneratePayslipRequest
	(*GeneratePayslipResponse)(nil),               // 1: payslip.v1.GeneratePayslipResponse
	(*SendPaylipRequest)(nil),                     // 2: payslip.v1.SendPaylipRequest
	(*SendPayslipResponse)(nil),                   // 3: payslip.v1.SendPayslipResponse
	(*GetPayslipRequest)(nil),                     // 4: payslip.v1.GetPayslipRequest
	(*GetPayslipResponse)(nil),                    // 5: payslip.v1.GetPayslipResponse
	(*GeneratePayslipRequest_OrderData)(nil),      // 6: payslip.v1.GeneratePayslipRequest.OrderData
	(*GeneratePayslipRequest_OrderData_Item)(nil), // 7: payslip.v1.GeneratePayslipRequest.OrderData.Item
}
var file_payslip_v1_payslip_proto_depIdxs = []int32{
	6, // 0: payslip.v1.GeneratePayslipRequest.order:type_name -> payslip.v1.GeneratePayslipRequest.OrderData
	7, // 1: payslip.v1.GeneratePayslipRequest.OrderData.items:type_name -> payslip.v1.GeneratePayslipRequest.OrderData.Item
	0, // 2: payslip.v1.DocumentService.GeneratePayslip:input_type -> payslip.v1.GeneratePayslipRequest
	2, // 3: payslip.v1.DocumentService.SendPayslip:input_type -> payslip.v1.SendPaylipRequest
	4, // 4: payslip.v1.DocumentService.GetPayslip:input_type -> payslip.v1.GetPayslipRequest
	1, // 5: payslip.v1.DocumentService.GeneratePayslip:output_type -> payslip.v1.GeneratePayslipResponse
	3, // 6: payslip.v1.DocumentService.SendPayslip:output_type -> payslip.v1.SendPayslipResponse
	5, // 7: payslip.v1.DocumentService.GetPayslip:output_type -> payslip.v1.GetPayslipResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payslip_v1_payslip_proto_init() }
func file_payslip_v1_payslip_proto_init() {
	if File_payslip_v1_payslip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payslip_v1_payslip_proto_rawDesc), len(file_payslip_v1_payslip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payslip_v1_payslip_proto_goTypes,
		DependencyIndexes: file_payslip_v1_payslip_proto_depIdxs,
		MessageInfos:      file_payslip_v1_payslip_proto_msgTypes,
	}.Build()
	File_payslip_v1_payslip_proto = out.File
	file_payslip_v1_payslip_proto_goTypes = nil
	file_payslip_v1_payslip_proto_depIdxs = nil
}
